# Generated by Django 5.0.1 on 2024-04-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_redeemed',
            field=models.BooleanField(default=True),
        ),
    ]
