# Generated by Django 5.0.1 on 2024-04-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_remove_coupon_is_redeemed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_coupon',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
