# Generated by Django 5.0.1 on 2024-02-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0002_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.TextField(max_length=15),
        ),
    ]
