# Generated by Django 5.0.1 on 2024-02-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0004_alter_account_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_emailverified',
            field=models.BooleanField(default=False),
        ),
    ]
