# Generated by Django 5.0.1 on 2024-04-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Authentication', '0007_order_payment_orderproduct_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='referral_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
