# Generated by Django 5.0.1 on 2024-05-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rprice',
            field=models.IntegerField(null=True),
        ),
    ]
