# Generated by Django 5.0.1 on 2024-05-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_rprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rprice',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
