# Generated by Django 5.0.1 on 2024-05-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_rprice_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
